{
 "title": "Builds",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Builds",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT (revision_origin_id) FROM `kernelci.kernelci01.builds` \n"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT COUNT (revision_origin_id) / (SELECT COUNT (revision_origin_id) FROM `kernelci.kernelci01.builds`) FROM `kernelci.kernelci01.builds` WHERE valid=true \n"
    }
   ]
  },
  {
   "title": "Builds per arch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "#standardSQL\r\nSELECT\r\n TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(`start_time`), 10800) * 10800),\r\n  CAST (`architecture`AS String ) AS metric,\r\n  count(`architecture`) AS architecture\r\nFROM `kernelci.kernelci01.builds`\r\nWHERE\r\n  `start_time` BETWEEN TIMESTAMP_MILLIS (1563028960953) AND TIMESTAMP_MILLIS (1570804960953) AND\r\n  start_time > '2019-08-01 00:00:00.000'\r\nGROUP BY 1,2\r\nORDER BY 1,2 LIMIT 797"
    }
   ]
  },
  {
   "title": "Builds per revisions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "#standardSQL\r\nSELECT\r\n TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(`start_time`), 10800) * 10800),\r\n  CAST (`revision_origin_id`AS String ) AS metric,\r\n  count(`revision_origin_id`) AS architecture\r\nFROM `kernelci.kernelci01.builds`\r\nGROUP BY 1,2\r\nORDER BY 1,2 LIMIT 797"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT revision_origin_id, MAX(start_time), COUNT(revision_origin_id), COUNT(valid), COUNT(revision_origin_id) - COUNT(valid), ARRAY_AGG(origin_id LIMIT 1)[OFFSET(0)]  FROM `kernelci.kernelci01.builds` GROUP BY revision_origin_id "
    }
   ]
  }
 ]
}